### ISSUE TITLE
"Current Theme" drop down should be disabled when "Sync with Doki Theme" is enabled

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-icons-jetbrains#1]
### Your Environment

JetBrains Rider 2022.3 EAP 7
Build #RD-223.7401.6, built on November 1, 2022
Licensed to JetBrains Rider EAP user: Hannele Ruiz
Expiration date: December 1, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    rdclient.asyncActions=false
    vcs.empty.toolwindow.show=false
    ide.workspace.model.rbs.as.tree=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.30.0)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    io.acari.DDLCTheme (88.2-1.6.0)
    io.unthrottled.doki.icons (88.0.1-beta.1)

### How to reproduce.

- Open the DTI settings

### What is expected?

The "Current Theme" drop down should be disabled when "Sync with Doki Theme" is enabled, as it doesn't does anything when this option is active.

![image](https://user-images.githubusercontent.com/11861253/200331036-91806773-19c1-43d1-8f07-ca2afd3fd74c.png)

**Comment by Unthrottled** [comment]
Lol, my first thought was, "How did you get a hold if it already? I haven't published a release yet." Then I forgot I added a test upload to my custom repository. 🤦 

Anyways, this was a good idea, thanks!

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/200594994-f5568a45-f181-4013-aefa-e2d831ae54a9.png)
