### ISSUE TITLE
[Bug]: Python file icon remains default with the plugin

### ISSUE THREAD

**Issue by dolphinbird** [doki-theme/doki-theme-icons-jetbrains#117]
### Your Environment

PyCharm 2024.1 (Community Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to Zi
Subscription is active until April 19, 2025.
For educational use only.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  - ide.experimental.ui=true
 
Non-Bundled Plugins:
  - io.unthrottled.doki.icons (88.5-1.2.0)
  - com.github.catppuccin.jetbrains (3.2.3)
  - izhangzhihao.rainbow.brackets.lite (1.1.0)

### How to reproduce.

Step One: Open Project with
Step Two: Create Python file (.py)
The python file keeps its default colors
<img width="224" alt="Screenshot in which the python file's icon remains unchanged while the rest of the UI has the cute doki icons" src="https://github.com/doki-theme/doki-theme-icons-jetbrains/assets/145630695/6db118d0-5805-4087-965f-0e394ad0c07e">

### What is expected?

Previously, the python logo would change and it matched with the rest of the icons. After this update, it no longer does this and keeps the default icon. How it looks like loaded up on ver. 2023.3.5: 
<img width="173" alt="Screenshot with the expected python icon" src="https://github.com/doki-theme/doki-theme-icons-jetbrains/assets/145630695/225f89ec-1d29-445b-a672-c2ab981fe30c">

**Comment by Eta0** [comment]
It looks like a potentially similar issue came up for catppuccin theme, related to [this JetBrains bug (PY-44417)](https://youtrack.jetbrains.com/issue/PY-44417/IconProvider-doesnt-replace-Python-Icons), and was addressed in catppuccin/jetbrains-icons#26 by [adding](https://github.com/catppuccin/jetbrains-icons/blob/f9c1e0a3a2ee45ba8c05c8edae52e34e9079c44e/src/main/kotlin/com/github/catppuccin/jetbrains_icons/decorators/PythonProjectViewNodeDecorator.kt) and [registering](https://github.com/catppuccin/jetbrains-icons/blob/f9c1e0a3a2ee45ba8c05c8edae52e34e9079c44e/src/main/resources/META-INF/plugin.xml#L40-L43) a [`ProjectViewNodeDecorator`](https://plugins.jetbrains.com/docs/intellij/project-view.html), so maybe something similar could be used here. Although probably for a few more files than just ones named `.py`, like `.pyx` as well.
