### ISSUE TITLE
[Bug]: Not compatible with the version of your running IDE (IntelliJ IDEA 2024.3)

### ISSUE THREAD

**Issue by Lzyct** [doki-theme/doki-theme-icons-jetbrains#120]
### Your Environment

IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Licensed to Mudassir Mudassir
Subscription is active until September 25, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4000M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  suggest.all.run.configurations.from.context=true
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
  ide.experimental.ui.inter.font=true
  i18n.locale=
  org.toml.json.schema=false
  terminal.new.ui=true
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.intellij.notebooks.core (243.21565.180)
  com.intellij.plugins.xwinkeymap (211.4961.30)
  some.awesome (1.15)
  com.intellij.plugins.macoskeymap (241.13688.16)
  com.jetbrains.edu (2024.10-2024.3-23)
  com.daniel-espinoza.inline-error (0.4.0)
  com.github.catppuccin.jetbrains (3.4.0)
  com.linmilin.plugin.PreviewImage (1.0)
  org.jetbrains.plugins.go-template (243.21565.122)
  PythonCore (243.21565.211)
  com.jetbrains.rust (243.21565.136)
  ayu-dark (1.0.4)
  com.github.jmorjsm.rosepineintellij (0.1.0)
  com.markskelton.one-dark-theme (5.12.0)
  dev.j-a.swift (1.2.0.365-243)
  String Manipulation (9.14.1)
  Key Promoter X (2024.2.2)
  org.jetbrains.plugins.go (243.21565.211)
  org.jetbrains.plugins.ruby (243.21565.211)
  AceJump (3.8.19)
  IdeaVIM (2.16.0)
  org.jetbrains.IdeaVim-EasyMotion (1.16)
  eu.theblob42.idea.whichkey (0.10.3)
  com.herbert.george.flutter-snippets (2.0.0-stable-1)
  com.wakatime.intellij.plugin (15.0.3)
  Pythonid (243.21565.211)
  com.intellij.python.django (243.21565.129)
  com.intellij.aqua (243.21565.199)
  org.elixir_lang (20.0.0)
  R4Intellij (243.21565.211)
  com.intellij.grazie.pro (0.3.346)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  Dart (243.21565.120)
  com.localizely.flutter-intl (1.18.8-2024.2)
  com.intellij.bigdatatools.core (243.21565.211)
  com.intellij.lang.jsgraphql (243.21565.122)
  com.jetbrains.plugins.jslint (202.3)
  com.github.catppuccin.jetbrains_icons (1.10.0)
  pl.pszklarska.pubversionchecker (1.3.5)
  org.jetbrains.android (243.21565.214)
  com.android.tools.design (243.21565.214)
  com.haulmont.rcb (243.21565.120)
  mdx.js (243.21565.120)
  io.flutter (82.2.4)
  de.mariushoefler.flutter_enhancement_suite (1.7.0)
  nix-idea (0.4.0.16)
  com.jetbrains.php (243.21565.211)
  com.mallowigi (97.0.0)
  izhangzhihao.rainbow.brackets (2024.2.7-241)
  com.github.copilot (1.5.29.7524)
  zielu.gittoolbox (600.0.7+242)
Kotlin: 243.21565.193-IJ

### How to reproduce.

Step One: Install the latest version Build #IU-243.21565.193, built on November 13, 2024

![image](https://github.com/user-attachments/assets/7d7f3ae6-6915-4685-ac7b-8ec1724278c6)

### What is expected?

The app can be run normally

**Comment by Unthrottled** [comment]
You can manually install the plugin for now
https://github.com/doki-theme/doki-theme-icons-jetbrains/tree/v88.5-1.5.0?tab=readme-ov-file#installation

I'm going to run this on the new platform for a while and test it out before publishing it to the marketplace. 

Thanks for reporting!!!
