### ISSUE TITLE
[ICON]: css

### ISSUE THREAD

**Issue by ronakkothari123** [doki-theme/doki-theme-icons-jetbrains#20]
### Icon Path or AllIcons Field

AllIcons.FileTypes.Css

### What does it look like?

![css](https://user-images.githubusercontent.com/70562508/208413113-067de060-2707-4b7f-9ebf-98f708635484.svg)

### How to get to it?

Step One: Open Project
Step Two: Create CSS file

**Comment by Unthrottled** [comment]
Thanks for reporting, I probably missed this because I haven't done any front-end development in a while. I'll probably get to this later this week.

**Comment by ronakkothari123** [comment]
Sounds good!

**Comment by ronakkothari123** [comment]
By the way I love how this theme looks!
