### ISSUE TITLE
[ICON]: Java package-info/module-info.java

### ISSUE THREAD

**Issue by NekoCaffeine** [doki-theme/doki-theme-icons-jetbrains#22]
### Icon Path or AllIcons Field

AllIcons.FileTypes.Java (more complex judgments may be required)

### What does it look like?

![Icon](https://intellij-icons.jetbrains.design/icons/AllIcons/fileTypes/java.svg)

### How to get to it?

Step One: Open Project

**Comment by Unthrottled** [comment]
Got it thanks, will wait a little bit and batch up all icon requests and complete them then. Thanks for reporting.
