### ISSUE TITLE
[ICON]: TSX

### ISSUE THREAD

**Issue by Bloeckchengrafik** [doki-theme/doki-theme-icons-jetbrains#23]
### Icon Path or AllIcons Field

JavaScriptPsiIcons.Icons.FileTypes.TSX

### What does it look like?

![Icon](https://intellij-icons.jetbrains.design/icons/JavaScriptPsiIcons/icons/fileTypes/TSX.svg)

### What Plugin?

(Integrated into) WebStorm

### How to get to it?

Step One: Open WebStorm Project
Step Two: Create a .tsx file

**Comment by Unthrottled** [comment]
Got it thanks, will wait a little bit and batch up all icon requests and complete them then. Thanks for reporting.
