### ISSUE TITLE
[Bug?] File icons (`.java`) don't work when power saving mode is on

### ISSUE THREAD

**Issue by nopeless** [doki-theme/doki-theme-icons-jetbrains#30]
### Your Environment

IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to *******
Subscription is active until ********, 2023.
For educational use only.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    com.github.copilot (1.1.38.2229)
    io.acari.DDLCTheme (88.3-1.8.0)
    io.unthrottled.doki.icons (88.3-1.0.2)
    com.demonwav.minecraft-dev (2022.3-1.5.21)

Kotlin: 223-1.7.21-release-272-IJ8214.52

### How to reproduce.

Step One: Open Project
Step Two: turn on power saving mode
Step Three: restart IDE, check `.java` files

### What is expected?

I understand that file icons for `.java` don't show because they are dependent on the content of the file ex) class, enum

But other files such as `html` and `json` seem to appear just fine

I haven't read the code for this repository yet but I am assuming that it is retrieving the exact file type from a background service (that is disabled on power saving mode) and defaults to the IntelliJ file icon

Is it possible that when there is no background service is active it defaults to a Java file icon?

I'm willing to help on this issue

**Comment by Unthrottled** [comment]
https://user-images.githubusercontent.com/15972415/211160398-f562c861-3ad2-4bc4-ae4a-5b4b711bbdcc.mp4


Yeah, so this plugin works by just replacing the existing icons that the "background service" provides when it interprets the files and replaces the file glyph (the video I linked referenced that).  https://plugins.jetbrains.com/docs/intellij/themes-customize.html#custom-icons

 Think power saving mode disables that feature of the IDE. That applies to not just java but any language plugin that supports that (it did if for kotlin as well). 

I don't want anything fancy put into the plugin to accommodate that use case. Hazarding a guess that it won't be simple. Seeing as it need to override either the functionality of any language plugin or disabling a feature of the platform. I'd like to keep this plugin simple and easy to maintain. Thanks for understanding and taking the time to submit the issue.
