### ISSUE TITLE
[ICON]: Java package-info/module-info.class

### ISSUE THREAD

**Issue by NekoCaffeine** [doki-theme/doki-theme-icons-jetbrains#33]
### Icon Path or AllIcons Field

AllIcons.FileTypes.Java

### What does it look like?

![Icon](https://camo.githubusercontent.com/87b3d5e53690f1acaadcd2dc8ed6edd29f4e17433cd02905201586db4a89da7e/68747470733a2f2f696e74656c6c696a2d69636f6e732e6a6574627261696e732e64657369676e2f69636f6e732f416c6c49636f6e732f66696c6554797065732f6a6176612e737667)

### How to get to it?

Step One: Open Project

**Comment by Unthrottled** [comment]
I added this in #27 

![Image](https://user-images.githubusercontent.com/15972415/210187342-6abe8179-0e36-4d42-a76e-24bebcee3e2b.png)

Are you wanting something different?

**Comment by NekoCaffeine** [comment]
Oh, this time it's `.class` not `.java`.

**Comment by Unthrottled** [comment]
Think that it's odd that it uses `/fileTypes/java.svg` and it does not use the coffee cup. Might be related to https://github.com/doki-theme/doki-theme-icons-jetbrains/issues/34#issuecomment-1384698137 at the moment.
