### ISSUE TITLE
[ICON]: dll/so/dylib

### ISSUE THREAD

**Issue by NekoCaffeine** [doki-theme/doki-theme-icons-jetbrains#34]
### Icon Path or AllIcons Field

AllIcons.FileTypes.Unknown

### What does it look like?

![Icon](https://intellij-icons.jetbrains.design/icons/AllIcons/fileTypes/unknown.svg)

### How to get to it?

Step One: Open Project

**Comment by Unthrottled** [comment]
Let me think about this one, because this affects all unknown file types.

**Comment by NekoCaffeine** [comment]
Can't be judged by the file name?

**Comment by Unthrottled** [comment]
Yeah, I originally built something that would allow that. However, dunno if that is something I want to support at the moment. I could see it growing. Let me think about it.
