### ISSUE TITLE
Cancel Build does not uses an icon similar to Build Solution

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-icons-jetbrains#4]
### Your Environment

JetBrains Rider 2022.3 EAP 8
Build #RD-223.7571.24, built on November 12, 2022
Licensed to JetBrains Rider EAP user: Hannele Ruiz
Expiration date: December 12, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.workspace.model.rbs.as.tree=false
    vcs.empty.toolwindow.show=false
    rdclient.asyncActions=false
    platform.projectModel.workspace.model.file.index=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.30.0)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    io.acari.DDLCTheme (88.2-1.6.0)
    io.unthrottled.doki.icons (88.2-1.0.0.beta.9)

### How to reproduce.

- Build a project in a supported IDE (in this case, I used Rider).

### What is expected?

The "Cancel Build" icon is similar to the "Build Solution" icon.

![image](https://user-images.githubusercontent.com/11861253/202838895-78f85825-0be8-4268-ac51-21b75dd1eccd.png)
![image](https://user-images.githubusercontent.com/11861253/202838902-9e5c75a4-217d-448a-acbf-64ca5104fa28.png)

**Comment by justalemon** [comment]
I submitted this as an Issue instead of an Icon Request because it's an icon discrepancy of an Icon that should actually be there.

(although I should probably have it submitted as an Icon Request so idk)

**Comment by Unthrottled** [comment]
> although I should probably have it submitted as an Icon Request

If it doesn't look like a Doki Icon, then please submit it as an Icon Request next time. 

I just did a quick search and found it:

<img width="1038" alt="Screenshot 2022-11-19 at 10 29 47 AM" src="https://user-images.githubusercontent.com/15972415/202861390-1e34b46b-abf8-43d2-adb2-f3ec6cb12ce8.png">

**Comment by justalemon** [comment]
> If it doesn't look like a Doki Icon, then please submit it as an Icon Request next time.

Okay! Sorry about that.

**Comment by Unthrottled** [comment]
<img width="245" alt="Screenshot 2022-11-20 at 11 05 47 AM" src="https://user-images.githubusercontent.com/15972415/202915693-b27f1162-4ff8-48a3-9f88-2965bbe132f0.png">

Just pushed out an update that includes this icon.
