### ISSUE TITLE
[Bug]: More tool windows icon is huge

### ISSUE THREAD

**Issue by jtth** [doki-theme/doki-theme-icons-jetbrains#47]
### Your Environment

IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to Jordan T. Thevenow-Harrison
Subscription is active until April 22, 2023.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.paperetto.dash (3.3)
    org.intellij.plugins.hcl (223.8214.6)
    net.vektah.codeglance2 (1.5.5)
    name.kropp.intellij.makefile (223.8214.6)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    AceJump (3.8.10)
    IdeaVIM (2.1.0)
    io.acari.DDLCTheme (88.3-1.8.0)
    io.unthrottled.amii (1.1.6)
    io.unthrottled.doki.icons (88.3-1.0.2)
    com.icg360.cryptor (1.2.1)
    net.ashald.envfile (3.4.1)
    CheckStyle-IDEA (5.75.0)
    com.atlassian.bitbucket.references (2022.1.220)
    com.intellij.bigdatatools (223.8214.65)
    com.haulmont.jpab (2022.5.4-223)
    org.sonarlint.idea (7.4.0.60471)
    com.cursiveclojure.cursive (1.12.7-2022.3)
    aws.toolkit (1.60-223)

Kotlin: 223-1.7.21-release-272-IJ8214.52

---

### How to reproduce.

Any time I open any project I get this in the left-hand toolbar. It happens across projects.

I don't think this icon should be this big.

<img width="317" alt="Screenshot 2023-02-10 at 09 43 32" src="https://user-images.githubusercontent.com/115188/218147786-cb00f04b-afaa-4070-91e9-ce86efe730af.png">

### What is expected?

The icon should be the same size as the other icons.

**Comment by Unthrottled** [comment]
![What did you do?](https://media.giphy.com/media/aJnQ9P7JVR25W/giphy.gif)

I've been using the New UI for a while now. How do you have it set up? I am currently not able to reproduce the issue. Maybe I need to update my MacBook?

<img width="1244" alt="Screenshot 2023-02-10 at 6 45 06 PM" src="https://user-images.githubusercontent.com/15972415/218227690-4390c54d-e01e-41be-8eb7-94c0c90602d9.png">


```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to Alex Simons
You have a perpetual fallback license for this version.
Subscription is active until February 20, 2024.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    io.acari.DDLCTheme (88.3-1.8.0)
    io.unthrottled.doki.icons (88.3-1.0.7)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Comment by Unthrottled** [comment]
Nope, that wasn't it.

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to Alex Simons
You have a perpetual fallback license for this version.
Subscription is active until February 20, 2024.
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    io.acari.DDLCTheme (88.3-1.8.0)
    io.unthrottled.doki.icons (88.3-1.0.7)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

**Comment by jtth** [comment]
Strange. I guess I'll uninstall and reinstall, but I didn't set anything up other than to check all the boxes and have it track based on the Doki theme :/ I'll update on Monday when I'm back on that machine.

**Comment by Unthrottled** [comment]
Thanks, try to manually install the latest update https://github.com/doki-theme/doki-theme-icons-jetbrains/releases/tag/v88.3-1.0.6 , that may or may not fix it (the platform has icon caching based on version, so it may still be big if you re-install the same version.)

**Comment by jtth** [comment]
@Unthrottled thank you, that worked! I uninstalled and reinstalled and all that dance and that did nothing, but manually installing from the latest update did it! Thank you so much!
