### ISSUE TITLE
[Bug]: "Select configuration element in tree to edit settings"

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-theme-icons-jetbrains#56]
### Your Environment

JetBrains Rider 2022.3.2
Build #RD-223.8617.53, built on January 25, 2023
Licensed to LemonUI / Hannele Ruiz
Subscription is active until May 22, 2023.
For non-commercial open source development only.
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.workspace.model.rbs.as.tree=false
    vcs.empty.toolwindow.show=false
    platform.projectModel.workspace.model.file.index=false
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false
    database.show.search.tab=false

Non-Bundled Plugins:
    io.unthrottled.theme.randomizer (0.8.1)
    com.intellij.settingsSync (223.8617.27)
    io.acari.DDLCTheme (88.3-1.9.3)
    io.unthrottled.doki.icons (88.3-1.0.9)

### How to reproduce.

Install both Doki Theme and Doki Icons in a clean ide from the Canary repo and open the Doki Theme Icon settings to get this:

![image](https://user-images.githubusercontent.com/11861253/220216448-1a7f3aa0-833a-4a74-8134-20f1a730a0fc.png)

### What is expected?

Configuration options are there

**Comment by Riccorbypro** [comment]
Getting the same issue, also Rider 2022.3.2. Have not tested the non-canary repo as this isn't a breaking issue, settings that have already been set seem to have been applied.

```
JetBrains Rider 2022.3.2
Build #RD-223.8617.53, built on January 25, 2023
Licensed to Richard Corbishley
You have a perpetual fallback license for this version.
Subscription is active until July 17, 2025.
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    ide.tooltip.initialDelay.highlighter=0
    search.everywhere.settings=true
    ide.experimental.ui=true
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false
    platform.projectModel.workspace.model.file.index=false
    vcs.empty.toolwindow.show=false
    ide.workspace.model.rbs.as.tree=false
    database.show.search.tab=false

Non-Bundled Plugins:
    com.intellij.javafx (1.0.4)
    com.intellij.resharper.HeapAllocationsViewer (2022.3.1)
    me.seclerp.rider.plugins.efcore (223.3.2)
    avalonia-rider (1.0.3.103)
    com.khmelyuk.multirun (1.13)
    com.intellij.ideolog (203.0.30.0)
    com.godwin.json.parser (1.4.1)
    cognitivecomplexity-rider (2022.3.0)
    String Manipulation (9.6.1)
    Abc.MoqComplete.Rider (2022.3.0.2)
    indent-rainbow.indent-rainbow (2.1.0)
    io.acari.DDLCTheme (88.3-1.9.3)
    io.unthrottled.amii (1.1.6)
    io.unthrottled.doki.icons (88.3-1.0.9)
    com.intellij.plugin.adernov.powershell (2.0.10)
    lermitage.intellij.battery.status (1.25)
    uk.co.ben-gibson.remote.repository.mapper (4.3.1)
    mobi.hsz.idea.gitignore (4.4.4)
    com.intellij.resharper.azure (3.50.0.1546-2022.3)

```
