### ISSUE TITLE
[Bug]: .java icons don't appear 

### ISSUE THREAD

**Issue by Zeltaria** [doki-theme/doki-theme-icons-jetbrains#68]
### Your Environment

IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Licensed to *********
Subscription is active until October 24, 2023.
For educational use only.
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Non-Bundled Plugins:
    manjaro.epb (1.7)
    com.github.tth05.minecraft-nbt-intellij-plugin (1.5.2)
    com.andrey4623.rainbowcsv (2.0.2)
    Key Promoter X (2023.1.0)
    indent-rainbow.indent-rainbow (2.1.0)
    io.acari.DDLCTheme (88.5-1.9.7)
    io.unthrottled.amii (1.1.7)
    io.unthrottled.doki.icons (88.5-1.0.12)
    ChatGPT (2.1.14-222.231)
    org.asciidoctor.intellij.asciidoc (0.38.12)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-231)
    izhangzhihao.rainbow.brackets (2023.2.6)
    com.demonwav.minecraft-dev (2023.1-1.6.3)
    com.mallowigi.colorHighlighter (15.0.0)
    com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.14.0)

Kotlin: 231-1.8.20-IJ8109.175

It should contain:
Windows 10/11 (I have same issue with both)
IntelliJ IDEA 2023.1
Doki Theme Icons 1.0.12
plugins: Anime memes, Ascii docs, COlor Highlighter, CSV editor, discord integration, Doki Theme, Doki Theme Icons, eevee Progress bar, Indent Rainbow, Rainbow bracket, PDF viewer, Rainbow CSV.

My issue is when I code in Java I have a icon who is not the one for java files and I don't know why!
![Capture](https://user-images.githubusercontent.com/43732249/231151808-0e4a8022-e281-449b-8aaa-a43ad8b983ba.PNG)

### How to reproduce.

Step One: Open Project
Step Two: See the Icons for .java file

### What is expected?

To have the right icon for java file.

**Comment by Unthrottled** [comment]
<img width="379" alt="Screenshot 2023-04-11 at 6 14 49 PM" src="https://user-images.githubusercontent.com/15972415/231308516-4ac19b8e-5b2d-434b-b6d1-8e35d6773e31.png">


I'm not really sure what you are asking about. That is the feature of the `File Glyphs` it replaces the PSI icons for the Java files. If you don't want that, then just turn off the feature in the settings. 

<img width="387" alt="Screenshot 2023-04-11 at 6 16 30 PM" src="https://user-images.githubusercontent.com/15972415/231308926-7198c859-18e8-4e2c-8988-f8804de3ea02.png">

**Comment by Zeltaria** [comment]
I mean that I see that you add icons for Java file (like the coffee cup) but I can't see it.
Maybe I did something wrong.

**Comment by Unthrottled** [comment]
Ah, the coffee cup only shows up when Intellij recognizes it as just a java file. The java plugin gives the file a different icon based on the content. The cup is just the default.

<img width="1058" alt="Screenshot 2023-04-16 at 1 34 58 PM" src="https://user-images.githubusercontent.com/15972415/232334361-0d4e2c24-df6e-4376-aed2-d8549beaf8f4.png">
